apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops
  labels:
    app: llmops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops
  template:
    metadata:
      labels:
        app: llmops
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
