apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  labels:
    app: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
