apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-migration
  labels:
    app: topic-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topic-migration
  template:
    metadata:
      labels:
        app: topic-migration
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
