apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai
  labels:
    app: openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai
  template:
    metadata:
      labels:
        app: openai
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
