apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cluster
  labels:
    app: multi-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-cluster
  template:
    metadata:
      labels:
        app: multi-cluster
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
