apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind
  labels:
    app: kind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kind
  template:
    metadata:
      labels:
        app: kind
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
