apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10-model-deployment-management
  labels:
    app: 10-model-deployment-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 10-model-deployment-management
  template:
    metadata:
      labels:
        app: 10-model-deployment-management
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
