apiVersion: apps/v1
kind: Deployment
metadata:
  name: terway-advanced
  labels:
    app: terway-advanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terway-advanced
  template:
    metadata:
      labels:
        app: terway-advanced
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
