upstream backend {
    server app1:80 weight=5;
    server app2:80 weight=5;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
