apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-networking
  labels:
    app: custom-networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-networking
  template:
    metadata:
      labels:
        app: custom-networking
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
