apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd
  labels:
    app: crd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crd
  template:
    metadata:
      labels:
        app: crd
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
