apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta
  labels:
    app: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta
  template:
    metadata:
      labels:
        app: meta
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
