apiVersion: apps/v1
kind: Deployment
metadata:
  name: 05-distributed-training-frameworks
  labels:
    app: 05-distributed-training-frameworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 05-distributed-training-frameworks
  template:
    metadata:
      labels:
        app: 05-distributed-training-frameworks
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
