apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemonset-basics
  labels:
    app: daemonset-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daemonset-basics
  template:
    metadata:
      labels:
        app: daemonset-basics
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
