apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluid
  labels:
    app: fluid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluid
  template:
    metadata:
      labels:
        app: fluid
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
