apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-best-practices
  labels:
    app: production-best-practices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-best-practices
  template:
    metadata:
      labels:
        app: production-best-practices
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
