apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-operations
  labels:
    app: production-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-operations
  template:
    metadata:
      labels:
        app: production-operations
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
