apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-detection-configuration
  labels:
    app: latency-detection-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-detection-configuration
  template:
    metadata:
      labels:
        app: latency-detection-configuration
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
