apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon
  labels:
    app: amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
