apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeskoop
  labels:
    app: kubeskoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeskoop
  template:
    metadata:
      labels:
        app: kubeskoop
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
