apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting
  labels:
    app: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting
  template:
    metadata:
      labels:
        app: troubleshooting
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
