apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-annotations
  labels:
    app: custom-annotations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-annotations
  template:
    metadata:
      labels:
        app: custom-annotations
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
