apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelscope
  labels:
    app: modelscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelscope
  template:
    metadata:
      labels:
        app: modelscope
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
