apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-infra
  labels:
    app: ai-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-infra
  template:
    metadata:
      labels:
        app: ai-infra
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
