upstream backend {
    least_conn;
    server app1:80 weight=3;
    server app2:80 weight=2;
    server app3:80 backup;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
    }
}
