global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@opendemo.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true
