apiVersion: apps/v1
kind: Deployment
metadata:
  name: regflow
  labels:
    app: regflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regflow
  template:
    metadata:
      labels:
        app: regflow
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
