apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-deletion
  labels:
    app: backup-deletion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-deletion
  template:
    metadata:
      labels:
        app: backup-deletion
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
