apiVersion: apps/v1
kind: Deployment
metadata:
  name: terway
  labels:
    app: terway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terway
  template:
    metadata:
      labels:
        app: terway
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
