apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsoft
  labels:
    app: microsoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsoft
  template:
    metadata:
      labels:
        app: microsoft
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
