apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow
  labels:
    app: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow
  template:
    metadata:
      labels:
        app: kubeflow
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
