apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-auth
  labels:
    app: rbac-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-auth
  template:
    metadata:
      labels:
        app: rbac-auth
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
