apiVersion: apps/v1
kind: Deployment
metadata:
  name: tencent
  labels:
    app: tencent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tencent
  template:
    metadata:
      labels:
        app: tencent
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
