apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-framework
  labels:
    app: operator-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-framework
  template:
    metadata:
      labels:
        app: operator-framework
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
