apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-spire-identity
  labels:
    app: spiffe-spire-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-spire-identity
  template:
    metadata:
      labels:
        app: spiffe-spire-identity
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
