apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-controllers
  labels:
    app: core-controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-controllers
  template:
    metadata:
      labels:
        app: core-controllers
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
