apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-gitops
  labels:
    app: argocd-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-gitops
  template:
    metadata:
      labels:
        app: argocd-gitops
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
