apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-service-mesh
  labels:
    app: cilium-service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium-service-mesh
  template:
    metadata:
      labels:
        app: cilium-service-mesh
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
