apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac
  labels:
    app: rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac
  template:
    metadata:
      labels:
        app: rbac
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
