apiVersion: v1
kind: Secret
metadata:
  name: other-cli-secrets
  namespace: other-cli-system
type: Opaque
data:
  # 注意：实际部署时需要使用base64编码的值
  # 示例：echo -n "your-api-key" | base64
  cli-api-key: ${SECRET_PLACEHOLDER}
  github-token: ${SECRET_PLACEHOLDER}
  jwt-secret: ${SECRET_PLACEHOLDER}