apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture-fundamentals
  labels:
    app: architecture-fundamentals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architecture-fundamentals
  template:
    metadata:
      labels:
        app: architecture-fundamentals
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
