CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    age INT,
    phone VARCHAR(20),
    status VARCHAR(20) DEFAULT 'ACTIVE'
);
