apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduled-backup
  labels:
    app: scheduled-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduled-backup
  template:
    metadata:
      labels:
        app: scheduled-backup
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
