apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-logging
  labels:
    app: monitoring-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-logging
  template:
    metadata:
      labels:
        app: monitoring-logging
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
