apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubleshooting-monitoring
  labels:
    app: troubleshooting-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting-monitoring
  template:
    metadata:
      labels:
        app: troubleshooting-monitoring
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
