apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-hyperparameter-tuning
  labels:
    app: katib-hyperparameter-tuning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib-hyperparameter-tuning
  template:
    metadata:
      labels:
        app: katib-hyperparameter-tuning
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
