apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-cost-optimization
  labels:
    app: finops-cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-cost-optimization
  template:
    metadata:
      labels:
        app: finops-cost-optimization
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
