apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-snapshot-location
  labels:
    app: volume-snapshot-location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-snapshot-location
  template:
    metadata:
      labels:
        app: volume-snapshot-location
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
