apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini
  labels:
    app: gemini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
