apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-failure
  labels:
    app: control-plane-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane-failure
  template:
    metadata:
      labels:
        app: control-plane-failure
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
