apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  labels:
    app: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
