apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistent-storage
  labels:
    app: persistent-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistent-storage
  template:
    metadata:
      labels:
        app: persistent-storage
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
