apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-serverless
  labels:
    app: knative-serverless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knative-serverless
  template:
    metadata:
      labels:
        app: knative-serverless
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
