apiVersion: apps/v1
kind: Deployment
metadata:
  name: 01-kubernetes-architecture-overview
  labels:
    app: 01-kubernetes-architecture-overview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 01-kubernetes-architecture-overview
  template:
    metadata:
      labels:
        app: 01-kubernetes-architecture-overview
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
