apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry
  labels:
    app: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry
  template:
    metadata:
      labels:
        app: opentelemetry
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
