apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
  labels:
    app: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
