apiVersion: apps/v1
kind: Deployment
metadata:
  name: network
  labels:
    app: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
