apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-provider
  labels:
    app: cloud-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-provider
  template:
    metadata:
      labels:
        app: cloud-provider
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
