apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-workflow
  labels:
    app: dev-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-workflow
  template:
    metadata:
      labels:
        app: dev-workflow
    spec:
      containers:
      - name: demo
        image: nginx:alpine
        ports:
        - containerPort: 80
